# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Mauro"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
    template_toolkit:
        ENCODING: utf8


plugins:
  DBIC:
    default:
      dsn: dbi:mysql:mauro
      schema_class: Mauro::MauroDB
      user: mauro
      pass: mauro
      options:
        RaiseError: 1
        PrintError: 1
        mysql_enable_utf8: 1
  Multilang: 
    languages: ['it', 'en'] 
    default: 'en' 

Strehler:
    admin_secured: 1
    languages: ['it', 'en']
    default_language: 'it'
    extra_menu:
        winery:
            auto: 0
            label: Cantine
            class: Mauro::Element::Winery
        wine:
            auto: 1
            label: Vini
            class: Mauro::Element::Wine
            categorized: 1
            publishable: 1
        
        

