ALTER TABLE `WINES` ENGINE = InnoDB;
ALTER TABLE `WINERYS` ENGINE = InnoDB;

CREATE INDEX category_for_wine ON WINES (CATEGORY);
ALTER TABLE `WINES` 
ADD CONSTRAINT category_of_wine FOREIGN KEY ( `CATEGORY` ) 
REFERENCES `CATEGORIES` (`ID` );

CREATE INDEX winery_for_wine ON WINES (WINERY);
ALTER TABLE `WINES` 
ADD CONSTRAINT winery_of_wine FOREIGN KEY ( `WINERY` ) 
REFERENCES `WINERYS` (`ID` );
