ALTER TABLE `ITALIAN_REGIONS` ENGINE = InnoDB;

CREATE INDEX region_for_wine ON WINES (ITALIAN_REGION);
ALTER TABLE `WINES` 
ADD CONSTRAINT region_of_wine FOREIGN KEY ( `ITALIAN_REGION` ) 
REFERENCES `ITALIAN_REGIONS` (`ID` );
